apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai
  labels:
    app: oai  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai
  template:
    metadata: 
      labels:
        app: oai
    spec:
      containers:
        - name: oai
          image: oaisoftwarealliance/oai-amf:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        - name: oai2
          image: oaisoftwarealliance/oai-nr-cuup:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        - name: oai3
          image: oaisoftwarealliance/oai-nr-ue:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
