apiVersion: apps/v1
kind: Deployment
metadata:
    - name: oai
      labels:
        app: oai  
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: oai
          image: oaisoftwarealliance/oai-amf:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

