apiVersion: apps/v1
kind: Deployment
metadata:
    name: oai
    labels:
       app: oai  
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: oai
          image: oaisoftwarealliance/oai-amf:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

--------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
    name: oai-service
    labels:
      app: oai
spec:
  type: NodePort
  selector:
    app: oai
  ports:
    - port: 8080
      targetPort: 8080